# Generated by Django 3.0.6 on 2020-06-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0117_auto_20200423_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=250),
            preserve_default=False,
        ),
    ]
