# Generated by Django 3.0.6 on 2020-06-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0117_auto_20200423_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='reference_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
