# Generated by Django 3.0.6 on 2020-06-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0118_product_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='code',
            new_name='product_code',
        ),
    ]
